
  name: first Workflow

on:
  workflow_dispatch:

jobs:
  firstjob:
     runs-on: ubuntu-latest
       steps:
         - name: firstJob script
           shell: bash
           run: echo Hello World! This is the first job
         - uses: actions/checkout@v4
               - name: Print to Log
                 id: print-to-log
                uses: actions/hello-world-javascript-action@main
                with:
                  who-to-greet: ${{ github.actor }} 

  secondjob:
    runs-on: ubuntu-latest
    steps:
      - name: second job
        shell: bash
        run: |
          echo second job
          echo and this is multi-line script
          
